---
name: nostromos
description: nostromOS
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 42

modules:
  - type: os-release
    properties:
      name: NostromOS
      pretty_name: NostromOS
      logo: nostromos-logo

  - type: files
    files:
      - source: system
        destination: /

- type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.google.Chrome
          - com.visualstudio.code

