---
name: nostromos
description: nostromOS
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 42

modules:
  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - kcalc
        - kate
        - elisa-player
        - gwenview
        - okular
        - kmines
        - kmahjongg
        - kpat
        - kcharselect
        - kcolorchooser
        - dragon
        - filelight
        - konversation
        - krdc
        - krfb

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.google.Chrome
          - com.visualstudio.code

  - type: signing
